spring:
  #Database settings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:defaultDB
    username: defaultUsername
    password: defaultPassword
  #LiquidBase settings
  liquibase:
    change-log: db.changelog/db.changelog-master.xml
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

server:
  port: 8082
